# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foxglove/FrameTransforms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from foxglove import FrameTransform_pb2 as foxglove_dot_FrameTransform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x66oxglove/FrameTransforms.proto\x12\x08\x66oxglove\x1a\x1d\x66oxglove/FrameTransform.proto\"?\n\x0f\x46rameTransforms\x12,\n\ntransforms\x18\x01 \x03(\x0b\x32\x18.foxglove.FrameTransformb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foxglove.FrameTransforms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FRAMETRANSFORMS._serialized_start=75
  _FRAMETRANSFORMS._serialized_end=138
# @@protoc_insertion_point(module_scope)
