"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import collections.abc
import foxglove.FrameTransform_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class FrameTransforms(google.protobuf.message.Message):
    """An array of FrameTransform messages"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSFORMS_FIELD_NUMBER: builtins.int
    @property
    def transforms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.FrameTransform_pb2.FrameTransform]:
        """Array of transforms"""
    def __init__(
        self,
        *,
        transforms: collections.abc.Iterable[foxglove.FrameTransform_pb2.FrameTransform] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["transforms", b"transforms"]) -> None: ...

global___FrameTransforms = FrameTransforms
