"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GeoJSON(google.protobuf.message.Message):
    """GeoJSON data for annotating maps"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GEOJSON_FIELD_NUMBER: builtins.int
    geojson: builtins.str
    """GeoJSON data encoded as a UTF-8 string"""
    def __init__(
        self,
        *,
        geojson: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["geojson", b"geojson"]) -> None: ...

global___GeoJSON = GeoJSON
