"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import collections.abc
import foxglove.CircleAnnotation_pb2
import foxglove.PointsAnnotation_pb2
import foxglove.TextAnnotation_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ImageAnnotations(google.protobuf.message.Message):
    """Array of annotations for a 2D image"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CIRCLES_FIELD_NUMBER: builtins.int
    POINTS_FIELD_NUMBER: builtins.int
    TEXTS_FIELD_NUMBER: builtins.int
    @property
    def circles(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.CircleAnnotation_pb2.CircleAnnotation]:
        """Circle annotations"""
    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.PointsAnnotation_pb2.PointsAnnotation]:
        """Points annotations"""
    @property
    def texts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.TextAnnotation_pb2.TextAnnotation]:
        """Text annotations"""
    def __init__(
        self,
        *,
        circles: collections.abc.Iterable[foxglove.CircleAnnotation_pb2.CircleAnnotation] | None = ...,
        points: collections.abc.Iterable[foxglove.PointsAnnotation_pb2.PointsAnnotation] | None = ...,
        texts: collections.abc.Iterable[foxglove.TextAnnotation_pb2.TextAnnotation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["circles", b"circles", "points", b"points", "texts", b"texts"]) -> None: ...

global___ImageAnnotations = ImageAnnotations
