"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class LocationFix(google.protobuf.message.Message):
    """A navigation satellite fix for any Global Navigation Satellite System"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PositionCovarianceType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PositionCovarianceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LocationFix._PositionCovarianceType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: LocationFix._PositionCovarianceType.ValueType  # 0
        APPROXIMATED: LocationFix._PositionCovarianceType.ValueType  # 1
        DIAGONAL_KNOWN: LocationFix._PositionCovarianceType.ValueType  # 2
        KNOWN: LocationFix._PositionCovarianceType.ValueType  # 3

    class PositionCovarianceType(_PositionCovarianceType, metaclass=_PositionCovarianceTypeEnumTypeWrapper):
        """Type of position covariance"""

    UNKNOWN: LocationFix.PositionCovarianceType.ValueType  # 0
    APPROXIMATED: LocationFix.PositionCovarianceType.ValueType  # 1
    DIAGONAL_KNOWN: LocationFix.PositionCovarianceType.ValueType  # 2
    KNOWN: LocationFix.PositionCovarianceType.ValueType  # 3

    TIMESTAMP_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    ALTITUDE_FIELD_NUMBER: builtins.int
    POSITION_COVARIANCE_FIELD_NUMBER: builtins.int
    POSITION_COVARIANCE_TYPE_FIELD_NUMBER: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of the message"""
    frame_id: builtins.str
    """Frame for the sensor. Latitude and longitude readings are at the origin of the frame."""
    latitude: builtins.float
    """Latitude in degrees"""
    longitude: builtins.float
    """Longitude in degrees"""
    altitude: builtins.float
    """Altitude in meters"""
    @property
    def position_covariance(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Position covariance (m^2) defined relative to a tangential plane through the reported position. The components are East, North, and Up (ENU), in row-major order.
        length 9
        """
    position_covariance_type: global___LocationFix.PositionCovarianceType.ValueType
    """If `position_covariance` is available, `position_covariance_type` must be set to indicate the type of covariance."""
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        frame_id: builtins.str = ...,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
        altitude: builtins.float = ...,
        position_covariance: collections.abc.Iterable[builtins.float] | None = ...,
        position_covariance_type: global___LocationFix.PositionCovarianceType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["altitude", b"altitude", "frame_id", b"frame_id", "latitude", b"latitude", "longitude", b"longitude", "position_covariance", b"position_covariance", "position_covariance_type", b"position_covariance_type", "timestamp", b"timestamp"]) -> None: ...

global___LocationFix = LocationFix
