"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Log(google.protobuf.message.Message):
    """A log message"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Level:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Log._Level.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Log._Level.ValueType  # 0
        DEBUG: Log._Level.ValueType  # 1
        INFO: Log._Level.ValueType  # 2
        WARNING: Log._Level.ValueType  # 3
        ERROR: Log._Level.ValueType  # 4
        FATAL: Log._Level.ValueType  # 5

    class Level(_Level, metaclass=_LevelEnumTypeWrapper):
        """Log level"""

    UNKNOWN: Log.Level.ValueType  # 0
    DEBUG: Log.Level.ValueType  # 1
    INFO: Log.Level.ValueType  # 2
    WARNING: Log.Level.ValueType  # 3
    ERROR: Log.Level.ValueType  # 4
    FATAL: Log.Level.ValueType  # 5

    TIMESTAMP_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FILE_FIELD_NUMBER: builtins.int
    LINE_FIELD_NUMBER: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of log message"""
    level: global___Log.Level.ValueType
    """Log level"""
    message: builtins.str
    """Log message"""
    name: builtins.str
    """Process or node name"""
    file: builtins.str
    """Filename"""
    line: builtins.int
    """Line number in the file"""
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        level: global___Log.Level.ValueType = ...,
        message: builtins.str = ...,
        name: builtins.str = ...,
        file: builtins.str = ...,
        line: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["file", b"file", "level", b"level", "line", b"line", "message", b"message", "name", b"name", "timestamp", b"timestamp"]) -> None: ...

global___Log = Log
