"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import foxglove.Quaternion_pb2
import foxglove.Vector3_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Pose(google.protobuf.message.Message):
    """A position and orientation for an object or reference frame in 3D space"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSITION_FIELD_NUMBER: builtins.int
    ORIENTATION_FIELD_NUMBER: builtins.int
    @property
    def position(self) -> foxglove.Vector3_pb2.Vector3:
        """Point denoting position in 3D space"""
    @property
    def orientation(self) -> foxglove.Quaternion_pb2.Quaternion:
        """Quaternion denoting orientation in 3D space"""
    def __init__(
        self,
        *,
        position: foxglove.Vector3_pb2.Vector3 | None = ...,
        orientation: foxglove.Quaternion_pb2.Quaternion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["orientation", b"orientation", "position", b"position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["orientation", b"orientation", "position", b"position"]) -> None: ...

global___Pose = Pose
