"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import collections.abc
import foxglove.Pose_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PosesInFrame(google.protobuf.message.Message):
    """An array of timestamped poses for an object or reference frame in 3D space"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    POSES_FIELD_NUMBER: builtins.int
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of pose"""
    frame_id: builtins.str
    """Frame of reference for pose position and orientation"""
    @property
    def poses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.Pose_pb2.Pose]:
        """Poses in 3D space"""
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        frame_id: builtins.str = ...,
        poses: collections.abc.Iterable[foxglove.Pose_pb2.Pose] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["frame_id", b"frame_id", "poses", b"poses", "timestamp", b"timestamp"]) -> None: ...

global___PosesInFrame = PosesInFrame
