"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import collections.abc
import foxglove.SceneEntityDeletion_pb2
import foxglove.SceneEntity_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SceneUpdate(google.protobuf.message.Message):
    """An update to the entities displayed in a 3D scene"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELETIONS_FIELD_NUMBER: builtins.int
    ENTITIES_FIELD_NUMBER: builtins.int
    @property
    def deletions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.SceneEntityDeletion_pb2.SceneEntityDeletion]:
        """Scene entities to delete"""
    @property
    def entities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[foxglove.SceneEntity_pb2.SceneEntity]:
        """Scene entities to add or replace"""
    def __init__(
        self,
        *,
        deletions: collections.abc.Iterable[foxglove.SceneEntityDeletion_pb2.SceneEntityDeletion] | None = ...,
        entities: collections.abc.Iterable[foxglove.SceneEntity_pb2.SceneEntity] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["deletions", b"deletions", "entities", b"entities"]) -> None: ...

global___SceneUpdate = SceneUpdate
