"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import foxglove.Color_pb2
import foxglove.Pose_pb2
import foxglove.Vector3_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SpherePrimitive(google.protobuf.message.Message):
    """A primitive representing a sphere or ellipsoid"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSE_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    @property
    def pose(self) -> foxglove.Pose_pb2.Pose:
        """Position of the center of the sphere and orientation of the sphere"""
    @property
    def size(self) -> foxglove.Vector3_pb2.Vector3:
        """Size (diameter) of the sphere along each axis"""
    @property
    def color(self) -> foxglove.Color_pb2.Color:
        """Color of the sphere"""
    def __init__(
        self,
        *,
        pose: foxglove.Pose_pb2.Pose | None = ...,
        size: foxglove.Vector3_pb2.Vector3 | None = ...,
        color: foxglove.Color_pb2.Color | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["color", b"color", "pose", b"pose", "size", b"size"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["color", b"color", "pose", b"pose", "size", b"size"]) -> None: ...

global___SpherePrimitive = SpherePrimitive
