"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Generated by https://github.com/foxglove/schemas"""
import builtins
import foxglove.Color_pb2
import foxglove.Pose_pb2
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TextPrimitive(google.protobuf.message.Message):
    """A primitive representing a text label"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POSE_FIELD_NUMBER: builtins.int
    BILLBOARD_FIELD_NUMBER: builtins.int
    FONT_SIZE_FIELD_NUMBER: builtins.int
    SCALE_INVARIANT_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    @property
    def pose(self) -> foxglove.Pose_pb2.Pose:
        """Position of the center of the text box and orientation of the text. Identity orientation means the text is oriented in the xy-plane and flows from -x to +x."""
    billboard: builtins.bool
    """Whether the text should respect `pose.orientation` (false) or always face the camera (true)"""
    font_size: builtins.float
    """Font size (height of one line of text)"""
    scale_invariant: builtins.bool
    """Indicates whether `font_size` is a fixed size in screen pixels (true), or specified in world coordinates and scales with distance from the camera (false)"""
    @property
    def color(self) -> foxglove.Color_pb2.Color:
        """Color of the text"""
    text: builtins.str
    """Text"""
    def __init__(
        self,
        *,
        pose: foxglove.Pose_pb2.Pose | None = ...,
        billboard: builtins.bool = ...,
        font_size: builtins.float = ...,
        scale_invariant: builtins.bool = ...,
        color: foxglove.Color_pb2.Color | None = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["color", b"color", "pose", b"pose"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["billboard", b"billboard", "color", b"color", "font_size", b"font_size", "pose", b"pose", "scale_invariant", b"scale_invariant", "text", b"text"]) -> None: ...

global___TextPrimitive = TextPrimitive
